# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - catdogapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://catdogapp.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_bfe01af4da51401197492a7def873ae1 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0e4faf50469d4ab7bf5bc8d72e7220b5 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: catdogapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_bfe01af4da51401197492a7def873ae1 }}/catdogapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'catdogapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_87b59a5a73ad422e84665e881f67f44e }}
        images: 'catdogapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_bfe01af4da51401197492a7def873ae1 }}/catdogapp:${{ github.sha }}'